language: php

php:
  - 5.4

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install

script: phpunit --coverage-text

notifications:
  email:
    recipients:
      - schnieders.a@gmail.com
      - wolters.fl@gmail.com
      - mjm159@gmail.com
      - olavhoffmann@gmail.com
      - parvus23@gmail.com
    on_success: change
    on_failure: always
